### ISSUE TITLE
py3 compatibility

### ISSUE THREAD

**Issue by easyw** [DeepSOIC/Part-o-magic#24]
PoM is not py3 compatible.
I found two print without parenthesis in Observer.py, but I also catch this exception:

> Log: Init:      Initializing C:\Users\userC\AppData\Roaming\FreeCAD\Mod\Part-o-magic... failed
> Log: ----------------------------------------------------------------------------------------------------
> Log: Traceback (most recent call last):
>   File "<string>", line 120, in InitApplications
>   File "<string>", line 11, in <module>
>   File "C:\Users\userC\AppData\Roaming\FreeCAD\Mod\Part-o-magic\PartOMagic\__init__.py", line 19, in importAll
>     mod.importAll()
>   File "C:\Users\userC\AppData\Roaming\FreeCAD\Mod\Part-o-magic\PartOMagic\Gui\__init__.py", line 20, in importAll
>     from . import Observer
>   File "C:\Users\userC\AppData\Roaming\FreeCAD\Mod\Part-o-magic\PartOMagic\Gui\Observer.py", line 8, in <module>
>     from Utils import msgbox
> ModuleNotFoundError: No module named 'Utils'
> Log: ----------------------------------------------------------------------------------------------------
> Err: During initialization the error No module named 'Utils' occurred in C:\Users\userC\AppData\Roaming\FreeCAD\Mod\Part-o-magic\InitGui.py

**Comment by DeepSOIC** [comment]
most-important stuff works, closing.
