### ISSUE TITLE
Annoying popup

### ISSUE THREAD

**Issue by leoheck** [DeepSOIC/Part-o-magic#32]
After I installed your extension yesterday, I am seeing a really annoying popup. I had to remove your extension, I can't work with this. I save my files every single change, and I can't afford to answer the popup every time.

![image](https://user-images.githubusercontent.com/1277920/62014630-f751c080-b179-11e9-9955-593c98d8cdf1.png)

**Comment by DeepSOIC** [comment]
Hi!
After some changes to FC a few months ago, it is now possible to fix the issue the popup is all about. I'm marking it as a bug now.

**Comment by leoheck** [comment]
@DeepSOIC I use your extension just to replace sketches. I install, replace the sketch then I uninstall it. 
I do this because I can't use Freecad with it installed since this popup comes every time I save my design.

I use to save it every time I made a good feature. Actually I save all the time for any program I am using. I do this because programs will eventually break. 

Please, can you show what I have to do to remove this popup by myself? I will create a patch or something to apply every time I upgrade part-o-magic.

I also want to have more time with this plugin installed so I can discover other good features it has.

**Comment by DeepSOIC** [comment]
> Please, can you show what I have to do to remove this popup by myself? I will create a patch or something to apply every time I upgrade part-o-magic.

Just press "Stop" button, the popup should go away.

I will fix this for FC 0.19 eventually, I just don't have time for it now.

**Comment by leoheck** [comment]
Which "Stop" button? Where I find it?

**Comment by DeepSOIC** [comment]
on PoM workbench. 
![PartOMagic_DisableObserver](https://user-images.githubusercontent.com/8940427/71843892-f84a2f00-30d5-11ea-9a5e-a6655512104d.png)

**Comment by leoheck** [comment]
haha, thanks dude!
