### ISSUE TITLE
PartOMagic can't detect FC version number

### ISSUE THREAD

**Issue by leoheck** [DeepSOIC/Part-o-magic#41]
Maybe a minor issue, but I would like to report anyway.

![image](https://user-images.githubusercontent.com/1277920/77442031-e9b40f80-6dc8-11ea-97f6-f2c296f87bda.png)

Does it have any impact on the workbench?

**Comment by DeepSOIC** [comment]
It's a FreeCAD problem (packaging issue, revision number is missing). Part-o-magic in theory should be assuming a newest version, so it should work. But this area is very poorly tested, there may be issues.
