### ISSUE TITLE
Didn't deactivate active container popup window

### ISSUE THREAD

**Issue by leoheck** [DeepSOIC/Part-o-magic#42]
Is it possible to remove this window?

I save my designs very often, and I see this so much, it is annoying to have to click that every time. You can add a message to the Report View if this is important.

![image](https://user-images.githubusercontent.com/1277920/77771907-11ec7a00-7026-11ea-8730-fcbea40692bc.png)

**Comment by DeepSOIC** [comment]
Version? In 0.19, it shouldn't pop up, as the issue is solved there.
https://github.com/DeepSOIC/Part-o-magic/issues/32
commit 973e7a5a86a69d866d3fda75d8d0dc21053049a4

**Comment by leoheck** [comment]
Yeah, it is in 0.19.
Maybe because it didn't detect the whole version as I referenced in another issue.

![image](https://user-images.githubusercontent.com/1277920/77871683-352c4a80-721b-11ea-8188-02961041b6bc.png)

**Comment by DeepSOIC** [comment]
Can you please paste this to console and tell what happens (i.e., what is printed as a response):
```
PartOMagic.Base.Compatibility.tempovis_is_stacky()
```

**Comment by leoheck** [comment]
Sure, it is returning true, anything else?

![image](https://user-images.githubusercontent.com/1277920/77930353-2bd5c900-7281-11ea-9d91-abfeb74bd6ff.png)

**Comment by DeepSOIC** [comment]
hmm, that doesn't make sense at all, because
```
    def slotSavedDocument(self, doc): #emulated - called by polling timer when LastModifiedDate of document changes
        ...
        from PartOMagic.Base.Compatibility import tempovis_is_stacky
        if tempovis_is_stacky():
            return
        from PySide import QtGui
        mb = QtGui.QMessageBox()
        mb.setIcon(mb.Icon.Warning)
        mb.setText("It looks like you've just saved your project, but didn't deactivate active container. \n\n"...)
```
Can you post a step-by-step guide for absolute idiots on how to reproduce it?

**Comment by leoheck** [comment]
Sure

I use to open files from the terminal so (with version 0.19)
```freecad-daily file.FCStd```

I tested this, now, and nothing happens, it looks good.
- Open the files
- Change something like editing a Sketch,
- Then close the Sketch
- Then Ctrl+S (looks good)

But sometimes, I open it just by clicking in the file, (this loads 0.18.4, for me)
> Doing the same with the same file, looks good too.

Maybe it happens in a new/old/different file.
For some reason, I couldn't reproduce it again now.

I will come back when I have a procedure that generates the issue again.

**Comment by leoheck** [comment]
Now I know.

Create a new file, (I am using 0.18.4)
and start working on it.

- Create a Body
- Create some sketches and pads
- Ctrl+s to save it. 

And then this happens.

![image](https://user-images.githubusercontent.com/1277920/78410650-58704480-75e3-11ea-93ce-1c57fa91d98a.png)

**Comment by leoheck** [comment]
Sincerely, I forgot to double-check the plugin version in both Freecad versions. Maybe this is my issue, I will verify that when I have a chance.

**Comment by DeepSOIC** [comment]
There is a small chance it may be caused by leftover TempoVis.py in Mod/Show (where FC is installed). It was removed from FreeCAD source code (renamed to mTempoVis.py), but it may not be deleted when updating the installation. Its presence is usually not a problem, but in a very special case, where you open a project that was saved by older version of FreeCAD while a sketch was open, it is known to mess up opening sketches for the lifetime of the FC application instance. But I think it shouldn't be affecting this particular aspect of Part-o-magic (other aspects will be, because PoM heavily uses TempoVis).

**Comment by leoheck** [comment]
Hm interesting, I checked that and this is not the case. I am using the latest version of the plugin now, everything looks great.
