### ISSUE TITLE
PartOMagic failed to detect FC version number

### ISSUE THREAD

**Issue by allanlaal** [DeepSOIC/Part-o-magic#53]
when launching FreeCAD 0.19, Libs: 0.19R from terminal, I get:

`PartOMagic failed to detect FC version number: revision is zero / too low, minor version is unexpected.`

**Comment by DeepSOIC** [comment]
can you please post the full version info (Open the Help --> About FreeCAD menu then click on the "Copy to clipboard" button, and paste its content in the text input area. This will provide valuable information on your exact version and revision number, your operating system as well as FreeCAD's internal libraries.)

**Comment by allanlaal** [comment]
issue seems fixed in FreeCAD 0.20
